name: Pull Request
on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint --max-warnings 0
      - run: yarn format-check

#  test:
#    container: node:18
#    runs-on:
#      group: ubuntu-large-16
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version-file: .node-version
#          cache: 'yarn'
#      - run: yarn install --frozen-lockfile
#      - run: yarn test
