name: Promote QA to Prod
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

run-name: Deploying ${{ inputs.image-tag }}
jobs:
  qa-image:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.image-tag }}
    steps:
      - name: QA Deploy Docker Image
        id: tag
        uses: skyfire-xyz/github-actions/get-last-deploy@main
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-name: sky-mcp-qa

  deploy:
    needs: [qa-image]
    uses: ./.github/workflows/render-deploy.yml
    with:
      environment: prod
      polling-interval: '30000'
      image-tag: ${{ needs.qa-image.outputs.image-tag }}
    secrets: inherit

  create-release:
    needs: [qa-image, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create Release Tag
        id: release-tag
        uses: skyfire-xyz/github-actions/create-release-tag@main
        with:
          ref: ${{ needs.qa-image.outputs.image-tag == 'latest' && 'main' || needs.qa-image.outputs.image-tag }}

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release-tag.outputs.tag-name }}
          generate_release_notes: true
