name: Promote QA to Sandbox
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

run-name: Deploying ${{ inputs.image-tag }}
jobs:
  qa-image:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.image-tag }}
    steps:
      - name: QA Deploy Docker Image
        id: tag
        uses: skyfire-xyz/github-actions/get-last-deploy@main
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-name: sky-mcp-qa

  deploy:
    needs: [qa-image]
    uses: ./.github/workflows/render-deploy.yml
    with:
      environment: sandbox
      polling-interval: '30000'
      image-tag: ${{ needs.qa-image.outputs.image-tag }}
    secrets: inherit
