name: Deploy Render Sandbox
on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Docker image tag to deploy'
        type: string

concurrency: ${{ github.workflow }}

run-name: Deploying ${{inputs.image-tag}}
jobs:
  deploy:
    uses: ./.github/workflows/render-deploy.yml
    with:
      environment: sandbox
      polling-interval: '30000'
      image-tag: ${{ inputs.image-tag }}
    secrets: inherit

  create-release:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # If the image tag is latest, we're deploying main
          # Otherwise, the imag-tag is the git ref
          ref: ${{ inputs.image-tag == 'latest' && 'main' || inputs.image-tag }}
          fetch-depth: 0

      - name: Git Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create Release Tag
        id: release-tag
        uses: skyfire-xyz/github-actions/create-release-tag@main
        with:
          ref: ${{ inputs.image-tag == 'latest' && 'main' || inputs.image-tag }}

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release-tag.outputs.tag-name }}
          generate_release_notes: true
