name: Deploy Render
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        description: Docker image tag to deploy. Defaults to latest
        required: true
        default: 'latest'
        type: string
      polling-interval:
        description: Polling interval in ms when checking Render deploy status
        default: '30000'
        type: string
    secrets:
      RENDER_API_KEY:
        required: true

run-name: Deploy ${{inputs.image-tag}} to ${{inputs.environment}}

jobs:
  start-deployment:
    runs-on: ubuntu-latest
    outputs:
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: render-${{ inputs.environment }}
          # If the image tag is latest, we're deploying the latest ref
          # Otherwise, the imag-tag is the git ref
          ref: ${{ inputs.image-tag == 'latest' && github.ref || inputs.image-tag }}

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          - service: sky-mcp-${{ inputs.environment }}

    steps:
      - uses: skyfire-xyz/github-actions/deploy@main
        name: Deploy ${{ matrix.services.service }}
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-name: ${{ matrix.services.service }}
          image: ghcr.io/${{ github.repository }}
          image-tag: ${{ inputs.image-tag}}
          wait-time: ${{ inputs.polling-interval }}

  finish-deployment:
    needs: [start-deployment, deploy]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: update deployment status
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ needs.deploy.result }}
          env: render-${{ inputs.environment }}
          ref: ${{ inputs.tag == 'latest' && github.ref || inputs.image-tag }}
          deployment_id: ${{ needs.start-deployment.outputs.deployment_id }}
